In [1]:
import sklearn.naive_bayes as nb
import pandas as pd
import numpy as np
import matplotlib as plt

In [98]:
adult_dat = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data', names=["Age", "Workclass", "fnlwgt", "Education", "Education-Num", "Martial Status",
        "Occupation", "Relationship", "Race", "Sex", "Capital Gain", "Capital Loss", "Hours per week", "Country", "Target"],
        sep=r'\s*,\s*', engine='python', na_values="?")

adult_dat.head()

Age         Workclass  fnlwgt  Education  Education-Num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       Martial Status         Occupation   Relationship   Race     Sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   Capital Gain  Capital Loss  Hours per week        Country Target  
0          2174             0              40  United-States  <=50K  
1             0             0              13  United-States  <=50K  
2             0             0              40  United-States  <=50K  
3             0             0              40  United-States  <=50K  
4             0             0              40           Cuba  <=50K

In [99]:
y = adult_dat['Target']
y.head()

0    <=50K
1    <=50K
2    <=50K
3    <=50K
4    <=50K
Name: Target, dtype: object

In [100]:
adult_dat.columns

Index([u'Age', u'Workclass', u'fnlwgt', u'Education', u'Education-Num',
       u'Martial Status', u'Occupation', u'Relationship', u'Race', u'Sex',
       u'Capital Gain', u'Capital Loss', u'Hours per week', u'Country',
       u'Target'],
      dtype='object')

In [101]:
columns = adult_dat.columns
for col in columns:
    x = adult_dat[[col for col in adult_dat.columns if col != 'Target']]
    
x.head()

Age         Workclass  fnlwgt  Education  Education-Num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       Martial Status         Occupation   Relationship   Race     Sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   Capital Gain  Capital Loss  Hours per week        Country  
0          2174             0              40  United-States  
1             0             0              13  United-States  
2             0             0              40  United-States  
3             0             0              40  United-States  
4             0             0              40           Cuba

In [103]:
from sklearn.preprocessing import OneHotEncoder

In [102]:
# not this, thinking of label encoder instead

enc = OneHotEncoder(handle_unknown='ignore')
one_hot = enc.fit_transform(x)

ValueError: invalid literal for long() with base 10: 'United-States'

In [104]:
from sklearn.preprocessing import LabelEncoder

In [105]:
le = LabelEncoder()

# need to encode y
# y = adult_dat['Target']

y = le.fit_transform(adult_dat['Target'])

In [106]:
df = pd.get_dummies(x)

In [107]:
df.shape

(32561, 105)

In [108]:
x.columns

Index([u'Age', u'Workclass', u'fnlwgt', u'Education', u'Education-Num',
       u'Martial Status', u'Occupation', u'Relationship', u'Race', u'Sex',
       u'Capital Gain', u'Capital Loss', u'Hours per week', u'Country'],
      dtype='object')

In [109]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [110]:
df.head()

Age  fnlwgt  Education-Num  Capital Gain  Capital Loss  Hours per week  \
0   39   77516             13          2174             0              40   
1   50   83311             13             0             0              13   
2   38  215646              9             0             0              40   
3   53  234721              7             0             0              40   
4   28  338409             13             0             0              40   

   Workclass_Federal-gov  Workclass_Local-gov  Workclass_Never-worked  \
0                    0.0                  0.0                     0.0   
1                    0.0                  0.0                     0.0   
2                    0.0                  0.0                     0.0   
3                    0.0                  0.0                     0.0   
4                    0.0                  0.0                     0.0   

   Workclass_Private         ...          Country_Portugal  \
0                0.0         ...                       0.0   
1                0.0         ...                       0.0   
2                1.0         ...                       0.0   
3                1.0         ...                       0.0   
4                1.0         ...                       0.0   

   Country_Puerto-Rico  Country_Scotland  Country_South  Country_Taiwan  \
0                  0.0               0.0            0.0             0.0   
1                  0.0               0.0            0.0             0.0   
2                  0.0               0.0            0.0             0.0   
3                  0.0               0.0            0.0             0.0   
4                  0.0               0.0            0.0             0.0   

   Country_Thailand  Country_Trinadad&Tobago  Country_United-States  \
0               0.0                      0.0                    1.0   
1               0.0                      0.0                    1.0   
2               0.0                      0.0                    1.0   
3               0.0                      0.0                    1.0   
4               0.0                      0.0                    0.0   

   Country_Vietnam  Country_Yugoslavia  
0              0.0                 0.0  
1              0.0                 0.0  
2              0.0                 0.0  
3              0.0                 0.0  
4              0.0                 0.0  

[5 rows x 105 columns]

In [122]:
from sklearn.preprocessing import StandardScaler

In [124]:
x = StandardScaler().fit_transform(df)

In [125]:
lda_sk = LinearDiscriminantAnalysis().fit_transform(x, y)

In [126]:
import matplotlib.pyplot as plt
%matplotlib inline

In [127]:
# plt.scatter(lda_sk[:,0], lda_sk[:, 1],
#            c=targets, cmap='viridis')

In [128]:
y

array([0, 0, 0, ..., 0, 0, 1])

In [129]:
# ok, so here is one column to model off of. 
# our target is either above 50,000 or below 50,000. Therefore, this will not give n_components=2 because
# LDA is (within sklearn’s implementation at least) 
#  limited to a set of components 1 less than the total number of classes  components= n -1

lda_sk

array([[-0.39313984],
       [ 1.17934116],
       [-1.23134466],
       ..., 
       [-0.85627293],
       [-1.35020454],
       [ 2.32050165]])

In [133]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.cross_validation import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [131]:
x_train, x_test, y_train, y_test = train_test_split(x,y)

In [132]:
rf = RandomForestClassifier()
rf.fit(x_train, y_train)
rf.score(x_train, y_train)

0.98710073710073709

In [134]:
rf.score(x_test, y_test)

0.84743888957130575

In [136]:
# confusion_matrix(y_test, rfc.predict(x_test))
confusion_matrix(y_test, rf.predict(x_test))

array([[5769,  449],
       [ 793, 1130]])

In [140]:
classification_report(y_test, y)

ValueError: Found arrays with inconsistent numbers of samples: [ 8141 32561]