In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('../DSI-CHI-1/lessons/week-07/2.1-dimensionality-reduction/assets/datasets/iris.csv')

In [2]:
df.head()

SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [4]:
x = df.ix[:,0:4].values
# just see a taste of  what I did
x[0:3]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2]])

In [5]:
# now we transform and standardize so they have mean 0 variance 1
from sklearn.preprocessing import StandardScaler

x_standard = StandardScaler().fit_transform(x)
# just transformed versions of above x's. except unit changes here are meaningful and can be compared
# difference in change between each number is the same scale
x_standard[0:5]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

In [6]:
# columns vs column and how much each one co-varies with each other
# flipping matrix

cov_mat = np.cov(x_standard.T)

In [7]:
cov_mat
# as sepal length goes up sepal width goes down 
# petal length and width are related

array([[ 1.00671141, -0.11010327,  0.87760486,  0.82344326],
       [-0.11010327,  1.00671141, -0.42333835, -0.358937  ],
       [ 0.87760486, -0.42333835,  1.00671141,  0.96921855],
       [ 0.82344326, -0.358937  ,  0.96921855,  1.00671141]])

In [8]:
# similar to what we did above

df.corr()

SepalLength  SepalWidth  PetalLength  PetalWidth
SepalLength     1.000000   -0.109369     0.871754    0.817954
SepalWidth     -0.109369    1.000000    -0.420516   -0.356544
PetalLength     0.871754   -0.420516     1.000000    0.962757
PetalWidth      0.817954   -0.356544     0.962757    1.000000

In [9]:
eigenValues, eigenVectors = np.linalg.eig(cov_mat)

In [12]:
# 

cov_mat[:,0]

array([ 1.00671141, -0.11010327,  0.87760486,  0.82344326])

In [10]:
# if we apply this transformation at the same point from cov_mat its the same as multiplying same point as eigen values

eigenVectors

array([[ 0.52237162, -0.37231836, -0.72101681,  0.26199559],
       [-0.26335492, -0.92555649,  0.24203288, -0.12413481],
       [ 0.58125401, -0.02109478,  0.14089226, -0.80115427],
       [ 0.56561105, -0.06541577,  0.6338014 ,  0.52354627]])

In [11]:
# found scaler transformations same as applying whole vector matrix

eigenValues

array([ 2.93035378,  0.92740362,  0.14834223,  0.02074601])

In [13]:
# total times changed. total scaler change

eigenValSum = sum(eigenValues)
eigenValSum

4.0268456375838948

In [15]:
eigenValues?

In [16]:
# take every eigen value and divide by each eigen value then multiply by 100 to get % = we get total amount of change

varianceExplained = [(i / eigenValSum) * 100 for i in sorted(eigenValues, reverse=True)]

In [17]:
# shows how much (%) each changed in cov_mat
# doesnt matter if by row or column

varianceExplained

[72.770452093801339, 23.03052326768065, 3.6838319576273775, 0.5151926808906323]

In [18]:
cumulativeVarianceExplained = np.cumsum(varianceExplained)

In [19]:
cumulativeVarianceExplained

array([  72.77045209,   95.80097536,   99.48480732,  100.        ])

In [ ]:
# what is most important column overall- eigen vectors!

In [21]:
eigenPairs = zip(eigenValues, eigenVectors)
eigenPairs

[(2.9303537755893174,
  array([ 0.52237162, -0.37231836, -0.72101681,  0.26199559])),
 (0.92740362151734212,
  array([-0.26335492, -0.92555649,  0.24203288, -0.12413481])),
 (0.14834222648163944,
  array([ 0.58125401, -0.02109478,  0.14089226, -0.80115427])),
 (0.020746013995595943,
  array([ 0.56561105, -0.06541577,  0.6338014 ,  0.52354627]))]

In [23]:
# grabbing ones that created most change

Pmatrix = np.hstack((eigenPairs[0][1].reshape(4,1),
                    eigenPairs[1][1].reshape(4,1)))
Pmatrix

array([[ 0.52237162, -0.26335492],
       [-0.37231836, -0.92555649],
       [-0.72101681,  0.24203288],
       [ 0.26199559, -0.12413481]])

In [27]:
# dot multiplication on original dataset
# set of two new columns with two new values encode same 95% variation we found 
# taking lessons we found in eigen values and applied it

x_standard[0].dot(Pmatrix)

array([-0.2316583 , -0.87967436])

In [28]:
x_standard[0]

array([-0.90068117,  1.03205722, -1.3412724 , -1.31297673])

heres the easy way!

In [30]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)

In [32]:
x_standard[0].dot(Pmatrix)

array([-0.2316583 , -0.87967436])

In [33]:
pca.fit_transform(x_standard)[0]

array([-2.26454173, -0.5057039 ])

In [34]:
pca.score(x_standard)

-3.6917727867613137

In [ ]:
PCA?

take data

how columns vary

use eigen vectors

use some of the eigan values

apply to data to decompose columns of importance