In [4]:
import pandas as pd
import numpy as np
import os
from matplotlib import pyplot as plt
%matplotlib inline
import numpy as np
import math
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA 

In [8]:
df = pd.read_csv('../DSI-CHI-1/lessons/week-07/2.3-pca-lab-1/assets/datasets/votes.csv', index_col=0)

In [9]:
df.head()

Class   V1 V2 V3   V4   V5 V6 V7 V8 V9 V10  V11  V12 V13 V14 V15  V16
1  republican    n  y  n    y    y  y  n  n  n   y  NaN    y   y   y   n    y
2  republican    n  y  n    y    y  y  n  n  n   n    n    y   y   y   n  NaN
3    democrat  NaN  y  y  NaN    y  y  n  n  n   n    y    n   y   y   n    n
4    democrat    n  y  y    n  NaN  y  n  n  n   n    y    n   y   n   n    y
5    democrat    y  y  y    n    y  y  n  n  n   n    y  NaN   y   y   y    y

In [10]:
# what should we do with all these NaN values...

df.isnull().sum()

Class      0
V1        12
V2        48
V3        11
V4        11
V5        15
V6        11
V7        14
V8        15
V9        22
V10        7
V11       21
V12       31
V13       25
V14       17
V15       28
V16      104
dtype: int64

In [11]:
for col in df.columns:
    df[col] = df[col].apply(lambda x: 1 if x == 'y' else 0)

In [12]:
df.head()

Class  V1  V2  V3  V4  V5  V6  V7  V8  V9  V10  V11  V12  V13  V14  V15  \
1      0   0   1   0   1   1   1   0   0   0    1    0    1    1    1    0   
2      0   0   1   0   1   1   1   0   0   0    0    0    1    1    1    0   
3      0   0   1   1   0   1   1   0   0   0    0    1    0    1    1    0   
4      0   0   1   1   0   0   1   0   0   0    0    1    0    1    0    0   
5      0   1   1   1   0   1   1   0   0   0    0    1    0    1    1    1   

   V16  
1    1  
2    0  
3    0  
4    1  
5    1

In [13]:
classes = pd.read_csv('../DSI-CHI-1/lessons/week-07/2.3-pca-lab-1/assets/datasets/votes.csv', index_col=0)

In [14]:
y = classes['Class']

In [16]:
x = df[[col for col in df.columns if col != 'Class']]
x.head()

V1  V2  V3  V4  V5  V6  V7  V8  V9  V10  V11  V12  V13  V14  V15  V16
1   0   1   0   1   1   1   0   0   0    1    0    1    1    1    0    1
2   0   1   0   1   1   1   0   0   0    0    0    1    1    1    0    0
3   0   1   1   0   1   1   0   0   0    0    1    0    1    1    0    0
4   0   1   1   0   0   1   0   0   0    0    1    0    1    0    0    1
5   1   1   1   0   1   1   0   0   0    0    1    0    1    1    1    1

In [17]:
napolean = StandardScaler().fit_transform(x)
napolean[0:5]

array([[-0.86835031,  1.10940039, -1.17902922,  1.20732229,  1.02561532,
         0.77412189, -1.10425892, -1.11977052, -0.9528351 ,  1.0069205 ,
        -0.72547625,  1.24252149,  1.03987485,  0.86835031, -0.81649658,
         0.78555736],
       [-0.86835031,  1.10940039, -1.17902922,  1.20732229,  1.02561532,
         0.77412189, -1.10425892, -1.11977052, -0.9528351 , -0.99312707,
        -0.72547625,  1.24252149,  1.03987485,  0.86835031, -0.81649658,
        -1.27298151],
       [-0.86835031,  1.10940039,  0.8481554 , -0.82827925,  1.02561532,
         0.77412189, -1.10425892, -1.11977052, -0.9528351 , -0.99312707,
         1.37840488, -0.80481505,  1.03987485,  0.86835031, -0.81649658,
        -1.27298151],
       [-0.86835031,  1.10940039,  0.8481554 , -0.82827925, -0.97502443,
         0.77412189, -1.10425892, -1.11977052, -0.9528351 , -0.99312707,
         1.37840488, -0.80481505,  1.03987485, -1.15160897, -0.81649658,
         0.78555736],
       [ 1.15160897,  1.10940039,  0

In [18]:
napolean.shape

(435, 16)

In [20]:
# create covariance matrix how often does one voting pattern predict the other

covariance_matrix = np.cov(napolean.T)
covariance_matrix[0:5]

array([[ 1.00230415,  0.0390487 ,  0.39852965, -0.39876866, -0.34579014,
        -0.3839277 ,  0.34852066,  0.39316258,  0.29835044, -0.08243094,
         0.11277752, -0.39554734, -0.32461413, -0.34420165,  0.22041201,
         0.04178208],
       [ 0.0390487 ,  1.00230415, -0.03206322,  0.07219786,  0.13871941,
         0.14423513, -0.18752265, -0.11640995, -0.18362303, -0.09106758,
         0.21209438, -0.02518596,  0.20689251, -0.01097236, -0.1134886 ,
        -0.06281611],
       [ 0.39852965, -0.03206322,  1.00230415, -0.70307903, -0.62891934,
        -0.42649531,  0.58200314,  0.69808179,  0.55748957,  0.03150538,
         0.21382384, -0.61638291, -0.51939642, -0.55892623,  0.47481813,
         0.15910551],
       [-0.39876866,  0.07219786, -0.70307903,  1.00230415,  0.76700038,
         0.47794019, -0.54909614, -0.69360128, -0.58441675,  0.05732038,
        -0.28650904,  0.68582975,  0.56288097,  0.63562536, -0.51508594,
        -0.11060219],
       [-0.34579014,  0.13871941, -0

In [21]:
covariance_matrix.shape

(16, 16)

In [22]:
# eigen 

eigenvalues, eigenvactors = np.linalg.eig(covariance_matrix)

In [23]:
# eqv to transforming it 7.10 times, etc
eigenvalues

array([ 7.102243  ,  1.44867882,  1.1998064 ,  0.88126251,  0.8248454 ,
        0.7380054 ,  0.14086407,  0.21188391,  0.61036665,  0.27622346,
        0.31858994,  0.35967328,  0.41340487,  0.54030753,  0.51431461,
        0.45639653])

In [24]:
eigenvalues.shape

(16,)

In [26]:
eigenvactors[0:3]

array([[-0.18803934, -0.19357121,  0.07328808,  0.51751543,  0.35845006,
         0.62089874, -0.05713493, -0.00747574,  0.15602045, -0.03613906,
        -0.07010134, -0.20296072,  0.12290505,  0.07348099,  0.20525446,
        -0.04760145],
       [ 0.05231849, -0.5860793 , -0.23045319,  0.37516036,  0.12646973,
        -0.55398342,  0.01855198, -0.10910015,  0.10486865,  0.0799821 ,
         0.0801356 , -0.13259865, -0.06581724,  0.07925709, -0.00808044,
         0.26963501],
       [-0.29660826, -0.08013044, -0.16884543, -0.01308925,  0.10990706,
         0.03068335, -0.2133564 , -0.06665988, -0.17958811, -0.23883742,
         0.56681358,  0.45295072,  0.08181081, -0.3596669 ,  0.23464645,
         0.08418781]])

In [27]:
eigenvactors.shape

(16, 16)

In [44]:
# find principal components

eigenpairs = zip(eigenvalues, eigenvactors)
eigenpairs

[(7.1022429960917224,
  array([-0.18803934, -0.19357121,  0.07328808,  0.51751543,  0.35845006,
          0.62089874, -0.05713493, -0.00747574,  0.15602045, -0.03613906,
         -0.07010134, -0.20296072,  0.12290505,  0.07348099,  0.20525446,
         -0.04760145])),
 (1.4486788186332424,
  array([ 0.05231849, -0.5860793 , -0.23045319,  0.37516036,  0.12646973,
         -0.55398342,  0.01855198, -0.10910015,  0.10486865,  0.0799821 ,
          0.0801356 , -0.13259865, -0.06581724,  0.07925709, -0.00808044,
          0.26963501])),
 (1.1998063964339236,
  array([-0.29660826, -0.08013044, -0.16884543, -0.01308925,  0.10990706,
          0.03068335, -0.2133564 , -0.06665988, -0.17958811, -0.23883742,
          0.56681358,  0.45295072,  0.08181081, -0.3596669 ,  0.23464645,
          0.08418781])),
 (0.88126250977162834,
  array([ 0.31510691,  0.1422561 ,  0.07340739,  0.13936979, -0.00770719,
         -0.05450439, -0.39727071,  0.4526401 ,  0.17904898, -0.55964437,
          0.01205996, 

In [31]:
for i in sorted(eigenpairs, reverse=True):
    print i

(7.1022429960917224, array([-0.18803934, -0.19357121,  0.07328808,  0.51751543,  0.35845006,
        0.62089874, -0.05713493, -0.00747574,  0.15602045, -0.03613906,
       -0.07010134, -0.20296072,  0.12290505,  0.07348099,  0.20525446,
       -0.04760145]))
(1.4486788186332424, array([ 0.05231849, -0.5860793 , -0.23045319,  0.37516036,  0.12646973,
       -0.55398342,  0.01855198, -0.10910015,  0.10486865,  0.0799821 ,
        0.0801356 , -0.13259865, -0.06581724,  0.07925709, -0.00808044,
        0.26963501]))
(1.1998063964339236, array([-0.29660826, -0.08013044, -0.16884543, -0.01308925,  0.10990706,
        0.03068335, -0.2133564 , -0.06665988, -0.17958811, -0.23883742,
        0.56681358,  0.45295072,  0.08181081, -0.3596669 ,  0.23464645,
        0.08418781]))
(0.88126250977162834, array([ 0.31510691,  0.1422561 ,  0.07340739,  0.13936979, -0.00770719,
       -0.05450439, -0.39727071,  0.4526401 ,  0.17904898, -0.55964437,
        0.01205996,  0.0780124 , -0.11191782,  0.25270932

In [32]:
# if we were to apply this to the whole 16 X 16 square it would scale it up this sum

eigansums = sum(eigenvalues)
eigansums

16.036866359446996

In [33]:
for eig in sorted(eigenpairs, reverse=True):
    print eig[0] / eigansums, eig[0]
    
# first transformation will give us 44% second 9%

0.442869750044 7.10224299609
0.0903342826562 1.44867881863
0.0748155138006 1.19980639643
0.054952288684 0.881262509772
0.051434325249 0.824845400306
0.0460193020622 0.738005397126
0.0380602190202 0.610366646038
0.033691590004 0.540307526332
0.0320707676532 0.5143146149
0.0284592089754 0.456396531035
0.0257784068163 0.413404865073
0.022427902783 0.359673279653
0.0198660966226 0.31858993662
0.0172242789882 0.276223460272
0.0132123011793 0.211883908313
0.00878376546217 0.140864072849


In [35]:
np.cumsum([(eig / eigansums) * 100 for eig in sorted(eigenvalues, reverse=True)])

array([  44.286975  ,   53.32040327,   60.80195465,   66.29718352,
         71.44061604,   76.04254625,   79.84856815,   83.21772715,
         86.42480392,   89.27072481,   91.8485655 ,   94.09135577,
         96.07796544,   97.80039334,   99.12162345,  100.        ])

In [ ]:
# how many components do we want? lets keep 8 for 83%

In [45]:
# fix this

# fit_me = [(eigenpairs[1].reshape(16,1)) for eigenpairs in sorted(eigenvalues, reverse=True)[0:8]]  

fit_me = []

for eigenpair in sorted(eigenpairs, reverse=True)[0:8]:
    fit_me.append(eigenpair[1].reshape(16,1))
    print eigenpair

(7.1022429960917224, array([-0.18803934, -0.19357121,  0.07328808,  0.51751543,  0.35845006,
        0.62089874, -0.05713493, -0.00747574,  0.15602045, -0.03613906,
       -0.07010134, -0.20296072,  0.12290505,  0.07348099,  0.20525446,
       -0.04760145]))
(1.4486788186332424, array([ 0.05231849, -0.5860793 , -0.23045319,  0.37516036,  0.12646973,
       -0.55398342,  0.01855198, -0.10910015,  0.10486865,  0.0799821 ,
        0.0801356 , -0.13259865, -0.06581724,  0.07925709, -0.00808044,
        0.26963501]))
(1.1998063964339236, array([-0.29660826, -0.08013044, -0.16884543, -0.01308925,  0.10990706,
        0.03068335, -0.2133564 , -0.06665988, -0.17958811, -0.23883742,
        0.56681358,  0.45295072,  0.08181081, -0.3596669 ,  0.23464645,
        0.08418781]))
(0.88126250977162834, array([ 0.31510691,  0.1422561 ,  0.07340739,  0.13936979, -0.00770719,
       -0.05450439, -0.39727071,  0.4526401 ,  0.17904898, -0.55964437,
        0.01205996,  0.0780124 , -0.11191782,  0.25270932

In [46]:
Pmatrix = np.hstack(fit_me)
Pmatrix

array([[-0.18803934,  0.05231849, -0.29660826,  0.31510691,  0.33401889,
         0.26716267, -0.29287877,  0.28769832],
       [-0.19357121, -0.5860793 , -0.08013044,  0.1422561 , -0.0385968 ,
        -0.07972083,  0.18058669,  0.14238328],
       [ 0.07328808, -0.23045319, -0.16884543,  0.07340739, -0.02237429,
        -0.25992991, -0.00924878, -0.13711492],
       [ 0.51751543,  0.37516036, -0.01308925,  0.13936979,  0.09559165,
        -0.19341153,  0.03611105,  0.00581328],
       [ 0.35845006,  0.12646973,  0.10990706, -0.00770719, -0.01349543,
         0.03386373,  0.01701353,  0.03355151],
       [ 0.62089874, -0.55398342,  0.03068335, -0.05450439,  0.13452608,
         0.03842238, -0.17373675,  0.24352607],
       [-0.05713493,  0.01855198, -0.2133564 , -0.39727071,  0.76511773,
        -0.07856633,  0.15624907, -0.08900957],
       [-0.00747574, -0.10910015, -0.06665988,  0.4526401 , -0.07320061,
         0.01950334, -0.28123287, -0.0304292 ],
       [ 0.15602045,  0.10486865

In [47]:
Pmatrix.shape

(16, 8)

In [48]:
pca_data = napolean.dot(Pmatrix)
pca_data

array([[ 1.00693395, -0.19192474,  0.52817463, ..., -0.49549519,
        -0.39141853, -0.02303219],
       [ 1.17720323, -0.9069469 ,  0.83255695, ..., -0.54600632,
         1.01127601, -1.225797  ],
       [ 0.54036052, -1.69772524,  0.78208641, ..., -0.75888437,
         2.04988555, -0.46274587],
       ..., 
       [ 1.32095962,  0.99518438,  2.35949456, ..., -0.76577894,
         0.52753876, -0.35613859],
       [ 1.4684445 ,  0.82658862,  1.16698618, ...,  0.02983416,
         0.25402801, -1.06204765],
       [ 1.10492339, -0.7469789 ,  0.35487075, ..., -0.91103396,
         0.00270789, -0.47308417]])

In [50]:
pca = PCA(n_components=8)
pca_x = pca.fit_transform(napolean)
pca_x[0:5]

array([[-3.57517112, -0.43829759,  1.00870171,  0.79092281, -0.05406329,
        -0.93318399, -0.55713373,  0.04677347],
       [-3.69493371,  0.89512838, -1.1943285 ,  0.09499978, -0.06831767,
        -0.8738653 ,  0.21938953,  0.26965817],
       [-1.7103028 ,  2.70058387,  0.26750866, -0.93407272, -0.04224974,
        -0.03776229,  1.02671695, -0.99280274],
       [-0.31396463,  2.31899467,  1.00095528, -0.13563217,  1.2273364 ,
        -0.68651566,  0.8140914 , -1.17273436],
       [-0.6784377 ,  2.53497808,  1.20162704,  0.50296716,  0.96102904,
         1.16778532, -0.70433166, -0.98979089]])

In [51]:
from sklearn.cluster import KMeans

regular_model = KMeans(2)

pca_model = KMeans(2)

In [56]:
def how_many_ones(x):
    ones = [y for y in x if y ==1]
    return len(ones) / float(len(x))

In [57]:
regular_model.fit(napolean)
how_many_ones(regular_model.labels_)


0.4735632183908046

In [60]:
pca_model.fit(pca_x)
how_many_ones(pca_model.labels_)

0.4735632183908046

In [61]:
y.value_counts()

democrat      267
republican    168
Name: Class, dtype: int64

In [62]:
pca = PCA(n_components=2)
pca_x = pca.fit_transform(napolean)
pca_x[0:5]

array([[-3.57517112, -0.43829759],
       [-3.69493371,  0.89512838],
       [-1.7103028 ,  2.70058387],
       [-0.31396463,  2.31899467],
       [-0.6784377 ,  2.53497808]])

In [63]:
regular_model = KMeans(2)

pca_model = KMeans(2)

In [64]:
def how_many_ones(x):
    ones = [y for y in x if y ==1]
    return len(ones) / float(len(x))

In [65]:
regular_model.fit(napolean)
how_many_ones(regular_model.labels_)

0.4735632183908046

In [66]:
pca_model.fit(pca_x)
how_many_ones(pca_model.labels_)

0.5310344827586206

In [67]:
y.value_counts()

democrat      267
republican    168
Name: Class, dtype: int64